# Generated by Django 5.2.7 on 2025-10-18 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='cost_cents',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='price_per_min',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='total_earnings',
        ),
        migrations.AddField(
            model_name='job',
            name='earnings_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='job',
            name='job_code',
            field=models.CharField(default='J-0000', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='progress_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='time_elapsed',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='base_clock_ghz',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='boost_clock_ghz',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='cuda_cores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='current_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_provider', to='api.job'),
        ),
        migrations.AddField(
            model_name='provider',
            name='gpu_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='jobs_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='temperature_c',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='provider',
            name='uptime_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_uri',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='output_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_jobs', to='api.provider'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='QUEUED', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='task_type',
            field=models.CharField(choices=[('ML_TRAINING', 'ML Training'), ('IMAGE_UPSCALE', 'Image Upscaling'), ('AI_RENDER', 'AI Rendering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='gpu_name',
            field=models.CharField(max_length=255),
        ),
    ]
