# Generated by Django 5.2.7 on 2025-10-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_job_cost_cents_remove_provider_price_per_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
