# Generated by Django 5.2.7 on 2025-10-19 00:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_provider_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('VISA', 'Visa'), ('MC', 'Mastercard')], max_length=8)),
                ('last_four', models.CharField(max_length=4)),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='api.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('this_month_spending', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='api.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.provider')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('provider', 'month')},
            },
        ),
    ]
